const grid = new GridTable()
grid.makeGridTable(6, 3, 'root', '1')
grid.insertData(1, 1, 'Item ID')
grid.insertData(2, 1, 666)
grid.insertData(3, 1, 333)
grid.updateHeader(['Item Name', 'Item Quantity', 'Item Price'])
grid.updateRow(2, ['Digimon', '500', '49.99'])
grid.updateRow(3, ['Yu-Gi-Oh', '460', '85.79'])
grid.updateRow(4, ['Airpods', '400', '3.49'])
grid.updateRow(5, ['Dungeons N Dragons', '920', '12.29'])
grid.updateRow(6, ['Beyblade', '129', '5.99'])
grid.sortData(1, 'desc')
grid.addRow(['Pokemon', 700, 26.99])
grid.addCol(['Item ID', 001, 002, 003, 004, 005, 006])
grid.sortData(4,'asc')

const weeklyCalendar = new GridTable()
weeklyCalendar.makeGridTable(16, 8, 'root', 'calendar')
weeklyCalendar.updateHeader(['', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'])
weeklyCalendar.updateCol(1, ['7:00AM', '8:00AM', '9:00AM', '10:00AM', '11:00AM', '12:00PM', '1:00PM', '2:00PM', '3:00PM', '4:00PM', '5:00PM', '6:00PM', '7:00PM', '8:00PM', '9:00PM'])
weeklyCalendar.addEvent({name: 'CSC301 Lecture', details: 'Introduction to Software Engineering'}, 13, 2)
weeklyCalendar.addEvent({name: 'CSC301 Tutorial', details: 'Introduction to Software Engineering'}, 15, 2)
weeklyCalendar.addEvent({name: 'CSC324 Tutorial', details: 'Functional Programming'}, 6, 2)
weeklyCalendar.addEvent({name: 'CSC309 Lecture', details: 'Intro to Web Programming'}, 11, 2)
weeklyCalendar.addEvent({name: 'CSC324 Lecture', details: 'Functional Programming'}, 6, 4)
weeklyCalendar.addEvent({name: 'CSC309 Lecture', details: 'Intro to Web Programming'}, 11, 4)
weeklyCalendar.addEvent({name: 'CSC324 Lecture', details: 'Functional Programming'}, 6, 6)
weeklyCalendar.addEvent({name: 'CSC309 Tutorial', details: 'Intro to Web Programming'}, 11, 6)
weeklyCalendar.deleteEvent(6, 2)
weeklyCalendar.modifyEvent({name: 'Untangle Money Meeting', details: 'Zoom Call'} ,13, 2)
// console.log(grid.cellData)
// 'Yu-Gi-Oh', '460', '85.79'